# SPDX-FileCopyrightText: Copyright (c) 2023 - 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

hydra:
    job:
          chdir: false
          # trained on 2018-2021 pressures and temporal context. select one day from each month to see the ensemble spreads
          name: generate_600_samples
    run:
          dir: ./hydra/${hydra:job.name}
    searchpath:
          - pkg://conf/base # Do not modify

# Base parameters for dataset, model, and generation
defaults:

    - dataset: hrrr_mini_raw

    - generation: non_patched
dataset:
    # data_path: /mnt/hrrr_era5_0528/hrrr_era5_calibration_2020.nc
    # # Path to .nc data file
    # stats_path: /mnt/hrrr_era5_0528/hrrr_era5_calibration_2020_stats.json
    data_path: /mnt/hrrr_era5_0528/hrrr_era5_test_2021.nc
    # Path to .nc data file
    stats_path: /mnt/hrrr_era5_0528/hrrr_era5_test_2021_stats.json
    # Path to json stats file
    input_variables: ["50u", "50v", "75u","75v", "100u", "100v", "125u", "125v", "150u", "150v","month_sin","month_cos","day_sin","day_cos"]
    output_variables: ["50u", "50v", "75u","75v", "100u", "100v", "125u", "125v", "150u", "150v"]
    # time_flag: True
    

# Generation parameters to specialize
bias_shape: [16,16]
generation:
    num_ensembles: 12
    # int, number of ensembles to generate per input
    seed_batch_size: 1
    inference_mode: "all" # bias for CorrDiffRegressionUNet, verifier for VerifierUNet
    hr_mean_conditioning: True
    load_all_times: False
    # int, size of the batched inference
    times:
    - "2021-05-02T00:00:00"
    - "2021-05-02T01:00:00"
    - "2021-05-02T02:00:00"
    - "2021-05-02T03:00:00"
    - "2021-05-02T04:00:00"
    - "2021-05-02T05:00:00"
    - "2021-05-02T06:00:00"
    - "2021-05-02T07:00:00"
    - "2021-05-02T08:00:00"
    - "2021-05-02T09:00:00"
    - "2021-05-02T10:00:00"
    - "2021-05-02T11:00:00"
    - "2021-05-02T12:00:00"
    - "2021-05-02T13:00:00"
    - "2021-05-02T14:00:00"
    - "2021-05-02T15:00:00"
    - "2021-05-02T16:00:00"
    - "2021-05-02T17:00:00"
    - "2021-05-02T18:00:00"
    - "2021-05-02T19:00:00"
    - "2021-05-02T20:00:00"
    - "2021-05-02T21:00:00"
    - "2021-05-02T22:00:00"
    - "2021-05-02T23:00:00"
    - "2021-05-03T00:00:00"
    - "2021-05-03T01:00:00"
    - "2021-05-03T02:00:00"
    - "2021-05-03T03:00:00"
    - "2021-05-03T04:00:00"
    - "2021-05-03T05:00:00"
    - "2021-05-03T06:00:00"
    - "2021-05-03T07:00:00"
    - "2021-05-03T08:00:00"
    - "2021-05-03T09:00:00"
    - "2021-05-03T10:00:00"
    - "2021-05-03T11:00:00"
    - "2021-05-03T12:00:00"
    - "2021-05-03T13:00:00"
    - "2021-05-03T14:00:00"
    - "2021-05-03T15:00:00"
    - "2021-05-03T16:00:00"
    - "2021-05-03T17:00:00"
    - "2021-05-03T18:00:00"
    - "2021-05-03T19:00:00"
    - "2021-05-03T20:00:00"
    - "2021-05-03T21:00:00"
    - "2021-05-03T22:00:00"
    - "2021-05-03T23:00:00"

    
        

    # List[str], time stamps in ISO 8601 format. Replace and list desired target
    # time stamps.
    io:
        output_filename: ./outputs/hrrr_mini_east/ble_generation_files/corrdif_residual_2021_BLErditfix2allpressures_temporal_50samples.nc
        res_ckpt_filename: /home/nvidia/projects/corrdiff_original/checkpoints/hrrr_mini_east_train/blepressures_temporal/checkpoints_diffusion/EDMPrecondSuperResolution.0.8000000.mdlus
        reg_ckpt_filename: /home/nvidia/projects/ReMatch/outputs/hrrr_era5/checkpoints/rematch_u/checkpoints_regression/CorrDiffRegressionUNet.0.3008.mdlus


# Parameters for wandb logging
wandb:
    mode: offline
    # Configure whether to use wandb: "offline", "online", "disabled"

swinir:
    checkpoint_path: null
    resume: null

    model_args:
        in_chans: 14
        out_chans: 10
        img_size: [21, 21]
        upscale: 8
        window_size: 7
        embed_dim: 180
        depths: [6, 6, 6, 6, 6, 6]
        num_heads: [6, 6, 6, 6, 6, 6]
        mlp_ratio: 2.0
        drop_path_rate: 0.0
        use_checkpoint: false
        multi_step_sampler: true
